ESCOMP/POP2-CESM

BranchChangeLog
cime_config/buildnml

For multi-instance runs, buildnml tries to copy marbl_in+inst_str files from popconf to run directory which fails because buildnml creates a single marbl_in file in popconf directory. Error message from IRT_N3_PM3_Ld7.f19_g17.BHIST.cheyenne_intel.allactive-defaultio :
```
Calling /gpfs/fs1/work/altuntas/cesm.sandboxes/cesm2.1-alphabranch/components/pop//cime_config/buildnml
grep: marbl_in_0001: No such file or directory
grep: marbl_in_0002: No such file or directory
grep: marbl_in_0003: No such file or directory
```
With this PR, a marbl_in+inst_str file is created for each instance in popconf and copied to rundir.
IRT_N3_PM3_Ld7.f19_g17.BHIST.cheyenne_intel.allactive-defaultio
SMS.f19_g17.BHIST.cheyenne_intel.allactive-defaultio
SMS.f19_g17.C.cheyenne_intel …

Fix marbl_in generation/copy for multi instance runs

---

bld/namelist_files/namelist_defaults_pop.xml

**Description of changes**:
update atmospheric carbon isotopic forcing files, changing format from cdf3 to cdf4
values are not changed
based on https://github.com/ESCOMP/ctsm/pull/737
**Testing**:
Test case/suite:
ERS_Ld30.T62_g37.C1850ECO.cheyenne_intel.pop-ciso_transient_abio_dic_dic14_transient
Fixes #2
User interface (namelist or namelist defaults) changes? yes
changes namelist defaults of
`ciso_atm_d13c_filename`
`ciso_atm_d14c_filename`
`abio_atm_d14c_filename`

change atm ciso filenames from cdf4 to cdf3

---

source/diag_bsf.F90

With this PR, the KMT values of eliminated land blocks are set to zero (instead of ```undefined_nf_int```) in ```island_mask_diag_bsf``` subroutine. The change is needed because the logic in ```island_mask_diag_bsf``` assumes all land cells are KMT=0.
Test case/suite: SMS_Lm1.f19_g17.B1850
Fixes: BSF diagnostics for large NTHRDS and NTASKS

Fixes BSF diagnostics for large NTHRDS and NTASKS

---

.gitignore
BranchChangeLog
cime_config/config_compsets.xml
cime_config/testdefs/testlist_pop.xml

`GOMIPECOIAF_JRA` was renamed to `GOMIPECOIAF_JRA-1p4-2018` in #14 but the testlist was not updated. (Also added `.gitignore` from `master`)
Test case/suite: generated all tests for `aux_pop` on cheyenne, verified that the `GOMIPECOIAF_JRA` failed but `GOMIPECOIAF_JRA-1p4-2018` was acceptable.
Test status: N/A (didn't actually run the tests, just created the cases for the tests)
No user interface (namelist or namelist defaults) changes

Fix bad compset name in cesm2_1 testlist

---

bld/build-namelist

With this change, build-namelist omits all dummy paths beginning with "unknown" and "same_as" in pop.input_data_list. No changes in pop namelist.
Test case/suite: aux_pop.cheyenne_intel
Fixes #23 
User interface (namelist or namelist defaults) changes? no

Omit dummy paths "unknown*" and "same_as*" in input_data_list

---

bld/build-namelist
bld/namelist_files/namelist_defaults_pop.xml
bld/namelist_files/namelist_definition_pop.xml
source/ecosys_forcing_mod.F90

Added two extra namelist variables to `ecosys_forcing_mod.F90` and gave two other existing variables clearer names to improve iron flux computation.
Test case/suite: `aux_pop` and `aux_pop_MARBL` (also built / ran a case on `hobart_nag`)
Test status: Definitely answer changing -- I presume not climate-changing
Fixes #17 
User interface (namelist or namelist defaults) changes? `iron_frac_in_atm_bc` and `iron_frac_in_seaice_bc` are no longer in the namelist, while `atm_bc_fe_bioavail_frac`, `atm_fe_to_bc_ratio`, `seaice_bc_fe_bioavail_frac`, and `seaice_fe_to_bc_ratio` are

Update ecosys forcing

---

BranchChangeLog
bld/build-namelist
bld/namelist_files/namelist_defaults_pop.xml
bld/namelist_files/namelist_definition_pop.xml
cime_config/testdefs/testlist_pop.xml
cime_config/testdefs/testmods_dirs/pop/abio_dic_dic14_ltavg_NK/include_user_mods
cime_config/testdefs/testmods_dirs/pop/abio_dic_dic14_ltavg_NK/user_nl_pop
input_templates/ocn.abio_dic_dic14.tavg.csh
source/abio_dic_dic14_mod.F90

Description of changes:
add tavg vars needed for Newton-Krylov solver to abio_dic_dic14
Move io_read_fallback_register_field call for 'ABIO_PH_SURF' outside of all_fields_exist_in_restfile conditional. This fallback should always be available, and the Newton-Krylov solver relies on it.
Testing:
Test case/suite: passes aux_pop on cheyenne/intel, compared to pop2_cesm2_1_rel_n10
new test ERS_Ld5_D.T62_g37.C.cheyenne_intel.pop-abio_dic_dic14_ltavg_NK added to aux_pop
Fixes: NA
computation and inclusion of vars in tavg file controlled with nml var abio_dic_dic14_ltavg_NK
(nml var not written to pop_in, just passed to tavg_contents generating script)

add Newton-Krylov solver related tavg vars to abio_dic_dic14

---

Externals_POP.cfg
bld/namelist_files/namelist_definition_pop.xml
drivers/mct/POP_CplIndices.F90
drivers/mct/ocn_import_export.F90
drivers/nuopc/ocn_import_export.F90
source/forcing_coupled.F90
source/forcing_fields.F90
source/vmix_kpp.F90

This pull request enables the parameterization of Langmuir turbulence induced entrainment by [Li and Fox-Kemper (2017)](https://doi.org/10.1175/JPO-D-17-0085.1) via CVMix. It includes the following changes:
- Point the CVMix repository to v0.97b-beta and update the CVMix interface in POP. A new interface of Langmuir turbulence parameterizations in CVMix was introduced in CVMix v0.94b-beta, allowing more options including Langmuir induced entrainment. See [this PR](https://github.com/CVMix/CVMix-src/pull/74) for more information.
- Get the surface layer averaged Langmuir number `LaSL` from WAVEWATCH III for Langmuir induced entrainment.
Test case/suite: See below
Test status: climate changing
Fixes [POP2 Github issue #]: N/A
- This …

Langmuir turbulence induced entrainment 

---

Externals_POP.cfg
bld/build-namelist
bld/namelist_files/namelist_defaults_pop.xml
cime_config/config_component.xml
cime_config/config_compsets.xml
cime_config/testdefs/testlist_pop.xml
cime_config/testdefs/testmods_dirs/pop/ecosys_add_cocco/shell_commands

This branch will update BGC configurations for the CESM2.2 release
1. `OCN_BGC_CONFIG=with_cocco` will use latest tunings with coccolithophores
1. `OCN_BGC_CONFIG=cesm2.1` will use same MARBL parameters as CESM 2.1 (though some bugfixes in POP will prevent bit-for-bit solutions when compared to CESM 2.1)
1. Provide a newly-created `init_ecosys_init_file` for `OCN_BGC_CONFIG=with_cocco`
1. Update `fesedflux_input%filename`
1. Update version of MARBL being used to latest available ([marbl0.39.0](https://github.com/marbl-ecosys/MARBL/releases/tag/marbl0.39.0))
1. Update `ecosys_add_cocco` to use latest tunings
1. Add `POP2%CESM21` compset option similar to `POP2%CESM20` (but to get `OCN_BGC_CONFIG=cesm2.1`)
* Create `C1850ECO_ECOCESM21` compset and test it in `aux_pop_MARBL`
Test case/suite: …

Bgc updates for cesm2 2

---

bld/namelist_files/namelist_defaults_pop.xml
cime_config/config_compsets.xml

`ndep_shr_stream_file` and `init_ecosys_init_file` were both, in some instances,
reading a netcdf-4 file, which is not compatible with pnetcdf and can
occasionally cause issues in PIO. I converted those files to cdf5 and updated
the namelist defaults file to read the new versions.
This matches the changes to default files included in #25 so `cesm2_1_x_rel` and `master`
will continue to use the same file (something in the CESM 2.2 build caused PIO to balk at reading netcdf-4 files; while that is not currently an issue in CESM 2.1, it could be in a future release)
Test case/suite: `aux_pop` and `aux_pop_MARBL` on cheyenne
Fixes N/A
-- namelist changes for all runs using gx1v7 resolution AND with `ecosys_on = …

Convert netcdf-4 file to cdf5, update nml defaults

---

bld/build-namelist
bld/namelist_files/namelist_defaults_pop.xml
cime_config/config_component.xml

Provide support for new `SSP534EXT` and `SSP585EXT` compsets -- the main goal was to provide a mechanism to set `dt_count=48` by default in the SSP585 extension.
I've provided branch tags to Mike Mills et al, who are testing the new compsets and think everything looks okay
Test case/suite: None
Test status: bit-for-bit
Fixes [POP2 Github issue #] N/A
****
I have two concerns relating to the robustness of this PR:
1. Setting `dt_count` via
```
<dt_count ocn_grid="gx1v7"  ocn_transient="ssp585ext">48</dt_count>
```
seems clunky, in the sense that it ignores other variables that might affect `dt_count`. In fact, I am confused why this value for `dt_count` wins out over
```
<dt_count ocn_ncpl="24" time_mix="robert" …
```

Update dt_count for RCP extensions

---

bld/namelist_files/namelist_defaults_pop.xml
bld/namelist_files/namelist_definition_pop.xml
cime_config/config_component.xml

Provide support for non-WACCM SSP534 compset, i.e. with `ndep_data_type=shr_stream`
sets `OCN_TRANSIENT=ssp534`, if compset longname starts with `SSP534_CAM`
adds namelist defaults for this `ocn_transisent` setting

Add support for OCN_TRANSIENT=ssp534

---

source/baroclinic.F90

Adds the missing impvmixu_tavg call needed for VUF and VVF outputs, and adds dd U2_2, V2_2 diags. This PR fixes the  momentum budget patch from 3fcd946
Test case/suite: c.e22.C.T62_g17 & subset of aux_mom
Test status: b4b

fix momentum budget output

---

drivers/nuopc/ocn_comp_nuopc.F90
drivers/nuopc/ocn_import_export.F90

This only effects the nuopc cap. The problem was that separate ndep fields were advertised (Faxa_nhx, Faxa_nox) and what should have been advertised is a single field (Faxa_ndep) with 2 undistributed dimensions for nhx and noy.
The following test were run and compared using cesm2_3_alpha03a and this pop PR code:
```
SMS_Vmct_Ln6.f19_g17.1850_CAM60%WCTS_CLM50%BGC-CROP_CICE_POP2%ECO%NDEP_MOSART_SGLC_WW3.cheyenne_intel.pop-default.validate
SMS_Vnuopc_Ln6.f19_g17.1850_CAM60%WCTS_CLM50%BGC-CROP_CICE_POP2%ECO%NDEP_MOSART_SGLC_WW3.cheyenne_intel.pop-default.validate
```
Test case/suite: Only test above was run
Test status: All other configurations should be bfbf
Fixes: None
User interface (namelist or namelist defaults) changes? No

fixed ndep problem for pop in nuopc cap

---

drivers/nuopc/ocn_comp_nuopc.F90
drivers/nuopc/ocn_import_export.F90

Additional bug fixes for ndep and co2 from cam -> pop for nuopc cap only
SMS_Vmct_Ln6.f19_g17.1850_CAM60_CLM50%BGC-CROP_CICE_POP2%ECO_MOSART_SGLC_WW3_BGC%BPRP.cheyenne_intel
SMS_Vnuopc_Ln6.f19_g17.1850_CAM60_CLM50%BGC-CROP_CICE_POP2%ECO_MOSART_SGLC_WW3_BGC%BPRP.cheyenne_intel
SMS_Vmct_Ld5.f19_g17.1850_CAM60%WCTS_CLM50%BGC-CROP_CICE_POP2%ECO%NDEP_MOSART_SGLC_WW3.cheyenne_intel.pop-default
SMS_Vnuopc_Ld5.f19_g17.1850_CAM60%WCTS_CLM50%BGC-CROP_CICE_POP2%ECO%NDEP_MOSART_SGLC_WW3.cheyenne_intel.pop-default
Test case/suite: Just ran above tests
Test status: Should not effect any other tests
Fixes:
User interface (namelist or namelist defaults) changes? None

Additional bug fixes for ndep and co2 from cam -> pop for nuopc cap

---

bld/generate_pop_decomp.xml
cime_config/config_pes.xml

Adding PE layouts and other necessary settings to run on UCI's cluster, [GreenPlanet](https://ps.uci.edu/greenplanet/). Currently supporting two of the [SLURM partitions](https://ps.uci.edu/greenplanet/slurm_partitions) (`sky2.4` and `sib2.9`), future PR may add `nes2.8` support as well.
Test case/suite: No full test suite, but I've run `C1850ECO` cases on both partitions using `gx3v7` and `gx1v7` resolutions. I'm happy to run `aux_pop` on cheyenne to verify I didn't break anything on that machine
Test status: N/A
Fixes [POP2 Github issue #] N/A
User interface (namelist or namelist defaults) changes? None

GreenPlanet support

---

cime_config/config_pes.xml
cime_config/testdefs/testlist_pop.xml
cime_config/testdefs/testlist_pop_nuopc.xml

All tests in the testlist_pop.xml and testlist_pop_nuopc.xml files that
previously ran on hobart now run on izumi. Also, the PE layouts in
config_pes.xml were moved from hobart to izumi (since they all used a multiple
of 48 tasks per component, and izumi has 48 cores per node)
I still need to test this on izumi, but I have a meeting coming up and then I'm off for a week and a half... so I'll set up the testing when I'm back at my desk. I mostly just want to test the PE layouts and make sure that throughput looks reasonable when running on izumi.
Fixes #57 
none

Config for izumi, not hobart

---

drivers/nuopc/ocn_import_export.F90

Added a single line to `drivers/nuopc/ocn_import_export.F90` to make sure `So_dhdy` is initialized to `_FillValue` before passing it to the coupler
[ Description of the changes in this Pull Request. It should be enough
information for someone not following this development to understand.]
Test case/suite:
Ran `SMS_Ld1_P136_D.T62_g17.C.cheyenne_intel.pop-144blocks_320x384_spacecurve` out of the box, verified that `ncview` balked at displaying `ocnImp_So_dhdy` with error
```
calculating min and maxes for ocnImp_So_dhdx.
netcdf_fi_get_data: error on nc_get_vara_float call
cdfid=65536   variable=ocnImp_So_dhdy
start, count:
[0]: 0  1
[1]: 0  384
[2]: 0  320
```
With this patch, the field can now be displayed (has missing values instead of extremely large values where land blocks were …

Initialize dataptr2(:)

---

drivers/nuopc/ocn_comp_nuopc.F90
drivers/nuopc/ocn_import_export.F90
source/POP_SolversMod.F90
source/damping.F90
source/overflows.F90
source/tidal_mixing.F90

Cleanup output to stdout.  This PR is intended to reduce the amount of data written to the cesm.log in 
production mode.  When DEBUG is defined all output is retained. 
Tested by hand using
ERS_D.f19_g17.B1850.cheyenne_intel.allactive-defaultio
Test case/suite: 
Fixes [POP2 Github issue #]
User interface (namelist or namelist defaults) changes?  NONE

clean up nuopc cap, reduce output to cesm.log file

---

BranchChangeLog
bld/generate_pop_decomp.xml
cime_config/config_pes.xml
cime_config/testdefs/testlist_pop.xml
cime_config/testdefs/testlist_pop_nuopc.xml

Added PE layouts for derecho, removed PE layouts for cheyenne, and updated testlist to move `cheyenne_intel` tests to `derecho_intel` and remove all other cheyenne tests (`intel` is only supported compiler for 2.2.z). I also updated `generate_pop_decomp.xml` to include a 128 PE layout for the `gx3v7` grid as well as some large PE layouts for `tx0.1v3`.
I ran `aux_pop` and verified that all tests ran successfully. I also did some performance testing, and can report the following throughput in different configurations (from `SMS_Ld20` and `SMS_Ld20_D` tests using the `pop/performance_eval` testmod directory)
| Resolution | C compset | G compset | C1850ECO compset | G 1850ECO compset |
| --- |  --- |  --- |  --- |  --- |
| T62_g37 | 388.97 SYPD | 338.97 SYPD | 120.49 SYPD | 126.08 SYPD |
| …

CESM 2.2.z: Add derecho support, remove cheyenne support

---

ChangeLog
bld/generate_pop_decomp.xml
cime_config/config_pes.xml
cime_config/testdefs/testlist_pop.xml
cime_config/testdefs/testlist_pop_nuopc.xml

Added PE layouts for derecho, removed PE layouts for cheyenne, updated testlist to move `cheyenne_*` tests to `derecho_*`, and then moved `derecho_pgi` to `derecho_nvhpc`. I also updated `generate_pop_decomp.xml` to include a 128 PE layout for the `gx3v7` grid as well as some large PE layouts for `tx0.1v3`.
I ran `aux_pop` and verified that all `intel` tests ran successfully; the `gnu` test built but did not run. I will investigate that later if it persists in the alpha testing for `cesm2_3_alpha17` series. I also did some performance testing, and can report the following throughput in different configurations (from `SMS_Ld20` and `SMS_Ld20_D` tests using the `pop/performance_eval` testmod directory)
| Resolution | C compset | G compset | C1850ECO compset | G 1850ECO compset |
| --- | …

 Add derecho support, remove cheyenne support
